[[donor]]
customer_id = "cus_QEBLqvEudErusz"
link = "https://www.fslabs.ca"
logo = "Foresight_Spatial_Labs.svg"

[[donor]]
customer_id = "cus_PihVbmEUk0vBkO"
logo = "dead_money.png"
link = "https://deadmoney.gg"
square_logo = true

[[donor]]
customer_id = "cus_Pl90EWRu326v6N"
logo = "cblogo.svg"

[[donor]]
customer_id = "cus_QCZaYjp4CCulkK"
logo = "holonautic.png"
logo_scale = 0.45

[[donor]]
customer_id = "cus_QIGvoRCqPjeUX0"
logo = "keygen.svg"

[[donor]]
customer_id = "cus_Q5reWVu1n5bNFp"
logo = "roids.png"
square_logo = true
