name: Update Donors

on:
  schedule:
    - cron:  '0 */4 * * *'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  update-donors:
    if: github.repository == 'bevyengine/bevy-donors'
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - name: Generate donors.toml and metrics.toml
        env:
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
        run: |
          cargo run

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            donors.toml
            metrics.toml
            logos/*
